set        Fatal {}
set      Warning {}
set         args /home/mooshak/crocker/test3.bin
set        input input
set       output output
set      context context
set       Points {}
set     Feedback {}
set         Show yes
